
version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vorkspay
      MYSQL_USER: vorkspay
      MYSQL_PASSWORD: vorkspay
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3333:3333"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/uploads:/app/uploads
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always

volumes:
  db_data:
